version: '3'
services:
    mysqldb:
        build: ./
        container_name: mysqldb
        command: --default-authentication-plugin=mysql_native_password
        restart: always
        environment:
            - MYSQL_DATABASE=stores
            - MYSQL_ROOT_PASSWORD=root
            - MYSQL_USER=store
            - MYSQL_PASSWORD=store
        ports:
            - 0.0.0.0:3000:3306
        expose:
            - "3000"
        volumes:
            - ./data/db/mysql:/var/lib/mysql
        networks:
            - my-network
networks:
    my-network:
        external: true