version: '3.8'
services:
  db:
    image: mysql:5.7
    cap_add:
      - SYS_NICE
    restart: always
    environment:
      - MYSQL_DATABASE=sigese
      - MYSQL_ROOT_PASSWORD=root
    ports:
      - '3306:3306'
    volumes:
      - db:/var/lib/mysql
    networks:
      - mysql-network
volumes:
  db:
    driver: local
networks:
    mysql-network:
        external: true
