version: '3.8'
services:
  mysql57:
    container_name: mysql57
    image: mysql:5.7
    cap_add:
      - SYS_NICE
    restart: always
    environment:
      MYSQL_ROOT_PASSWORD: root
      MYSQL_USER: admin
      MYSQL_PASSWORD: password
      MYSQL_DATABASE: mysql57
    ports:
      - "33067:3306"
    volumes:
      - ./docker/mysql/myconf.conf:/etc/mysql/conf.d/myconf.conf
      - db57:/var/lib/mysql
    networks:
      - mysql-network

  mysql80:
    container_name: mysql80
    restart: always
    image: mysql:8.0.31
    volumes:
      - ./docker/mysql/myconf.conf:/etc/mysql/conf.d/myconf.conf
      - db80:/var/lib/mysql
    command: --default-authentication-plugin=mysql_native_password
    environment:
      MYSQL_ROOT_PASSWORD: root
      MYSQL_USER: admin
      MYSQL_PASSWORD: password
      MYSQL_DATABASE: mysql80
    ports:
      - "33068:3306"
    networks:
      -  mysql-network
volumes:
  db57:
    driver: local
  db80:
      driver: local
networks:
  mysql-network:
    external: true
